# Generated by Django 4.2.21 on 2025-06-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresscoordinates',
            old_name='lan',
            new_name='lon',
        ),
    ]
