# Generated by Django 4.2.21 on 2025-05-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderitem_fixed_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='fixed_price',
        ),
    ]
