# Generated by Django 4.2.21 on 2025-06-02 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_remove_orderitem_fixed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фиксированная цена'),
        ),
    ]
