# Generated by Django 4.2.21 on 2025-06-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderitem_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_price',
            new_name='fixed_price',
        ),
    ]
