# Generated by Django 4.2.21 on 2025-06-02 13:21

from django.db import migrations


def populate_fixed_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.all():
        item.fixed_price = item.product.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_rename_order_price_orderitem_fixed_price'),
    ]

    operations = [
        migrations.RunPython(populate_fixed_price),
    ]
