# Generated by Django 4.2.21 on 2025-06-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_orderitem_fixed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('MANAGER', 'Менеджер'), ('RESTAURANT', 'Ресторан'), ('COURIER', 'Курьер'), ('COMPLETED', 'Завершён')], db_index=True, default='MANAGER', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
