# Generated by Django 4.2.21 on 2025-06-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Комментарий'),
        ),
    ]
