# Generated by Django 4.2.21 on 2025-06-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ELECTRONIC', 'Электронно'), ('CASH', 'Наличностью')], db_index=True, max_length=50, null=True, verbose_name='Способ оплаты'),
        ),
    ]
