# Generated by Django 4.2.21 on 2025-06-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ELECTRONIC', 'Электронно'), ('CASH', 'Наличностью')], db_index=True, default='', max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='контактный телефон'),
        ),
    ]
