# Generated by Django 4.2.21 on 2025-06-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_order_comment_alter_order_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта адреса'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота адреса'),
        ),
    ]
